package main

// we expect this to be invoked on OpcodeData
const tmplOpcodesEnabled = `
package vm

// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT EDIT.

import "github.com/oneiro-ndev/ndaumath/pkg/bitset256"

// EnabledOpcodes is a bitset of the opcodes that are enabled -- only these opcodes will be
// permitted in scripts.
var EnabledOpcodes = bitset256.New(
{{- range .Enabled}}
	byte(Op{{.Name}}),
{{- end}}
)
`
